// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import java.util.List;
import org.inqle.domain.LatestParticipantDatum;
import org.inqle.domain.LatestParticipantDatumDataOnDemand;
import org.inqle.domain.LatestParticipantDatumIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LatestParticipantDatumIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LatestParticipantDatumIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LatestParticipantDatumIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LatestParticipantDatumIntegrationTest: @Transactional;
    
    @Autowired
    LatestParticipantDatumDataOnDemand LatestParticipantDatumIntegrationTest.dod;
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testCountLatestParticipantDatums() {
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", dod.getRandomLatestParticipantDatum());
        long count = LatestParticipantDatum.countLatestParticipantDatums();
        Assert.assertTrue("Counter for 'LatestParticipantDatum' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testFindLatestParticipantDatum() {
        LatestParticipantDatum obj = dod.getRandomLatestParticipantDatum();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to provide an identifier", id);
        obj = LatestParticipantDatum.findLatestParticipantDatum(id);
        Assert.assertNotNull("Find method for 'LatestParticipantDatum' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LatestParticipantDatum' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testFindAllLatestParticipantDatums() {
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", dod.getRandomLatestParticipantDatum());
        long count = LatestParticipantDatum.countLatestParticipantDatums();
        Assert.assertTrue("Too expensive to perform a find all test for 'LatestParticipantDatum', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LatestParticipantDatum> result = LatestParticipantDatum.findAllLatestParticipantDatums();
        Assert.assertNotNull("Find all method for 'LatestParticipantDatum' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LatestParticipantDatum' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testFindLatestParticipantDatumEntries() {
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", dod.getRandomLatestParticipantDatum());
        long count = LatestParticipantDatum.countLatestParticipantDatums();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LatestParticipantDatum> result = LatestParticipantDatum.findLatestParticipantDatumEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LatestParticipantDatum' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LatestParticipantDatum' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testFlush() {
        LatestParticipantDatum obj = dod.getRandomLatestParticipantDatum();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to provide an identifier", id);
        obj = LatestParticipantDatum.findLatestParticipantDatum(id);
        Assert.assertNotNull("Find method for 'LatestParticipantDatum' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLatestParticipantDatum(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LatestParticipantDatum' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testMergeUpdate() {
        LatestParticipantDatum obj = dod.getRandomLatestParticipantDatum();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to provide an identifier", id);
        obj = LatestParticipantDatum.findLatestParticipantDatum(id);
        boolean modified =  dod.modifyLatestParticipantDatum(obj);
        Integer currentVersion = obj.getVersion();
        LatestParticipantDatum merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LatestParticipantDatum' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", dod.getRandomLatestParticipantDatum());
        LatestParticipantDatum obj = dod.getNewTransientLatestParticipantDatum(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LatestParticipantDatum' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'LatestParticipantDatum' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LatestParticipantDatumIntegrationTest.testRemove() {
        LatestParticipantDatum obj = dod.getRandomLatestParticipantDatum();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LatestParticipantDatum' failed to provide an identifier", id);
        obj = LatestParticipantDatum.findLatestParticipantDatum(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LatestParticipantDatum' with identifier '" + id + "'", LatestParticipantDatum.findLatestParticipantDatum(id));
    }
    
}
