// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import org.inqle.domain.SubscriptionIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SubscriptionIntegrationTest_Roo_Configurable {
    
    declare @type: SubscriptionIntegrationTest: @Configurable;
    
}
