// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.beyobe.domain;

import com.beyobe.domain.ParcelIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParcelIntegrationTest_Roo_Configurable {
    
    declare @type: ParcelIntegrationTest: @Configurable;
    
}
