// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import java.util.List;
import org.inqle.domain.Concept;
import org.inqle.domain.ConceptDataOnDemand;
import org.inqle.domain.ConceptIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConceptIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConceptIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConceptIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConceptIntegrationTest: @Transactional;
    
    @Autowired
    ConceptDataOnDemand ConceptIntegrationTest.dod;
    
    @Test
    public void ConceptIntegrationTest.testCountConcepts() {
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", dod.getRandomConcept());
        long count = Concept.countConcepts();
        Assert.assertTrue("Counter for 'Concept' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConceptIntegrationTest.testFindConcept() {
        Concept obj = dod.getRandomConcept();
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Concept' failed to provide an identifier", id);
        obj = Concept.findConcept(id);
        Assert.assertNotNull("Find method for 'Concept' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Concept' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConceptIntegrationTest.testFindAllConcepts() {
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", dod.getRandomConcept());
        long count = Concept.countConcepts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Concept', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Concept> result = Concept.findAllConcepts();
        Assert.assertNotNull("Find all method for 'Concept' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Concept' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConceptIntegrationTest.testFindConceptEntries() {
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", dod.getRandomConcept());
        long count = Concept.countConcepts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Concept> result = Concept.findConceptEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Concept' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Concept' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConceptIntegrationTest.testFlush() {
        Concept obj = dod.getRandomConcept();
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Concept' failed to provide an identifier", id);
        obj = Concept.findConcept(id);
        Assert.assertNotNull("Find method for 'Concept' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConcept(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Concept' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptIntegrationTest.testMergeUpdate() {
        Concept obj = dod.getRandomConcept();
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Concept' failed to provide an identifier", id);
        obj = Concept.findConcept(id);
        boolean modified =  dod.modifyConcept(obj);
        Integer currentVersion = obj.getVersion();
        Concept merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Concept' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", dod.getRandomConcept());
        Concept obj = dod.getNewTransientConcept(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Concept' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Concept' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Concept' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConceptIntegrationTest.testRemove() {
        Concept obj = dod.getRandomConcept();
        Assert.assertNotNull("Data on demand for 'Concept' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Concept' failed to provide an identifier", id);
        obj = Concept.findConcept(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Concept' with identifier '" + id + "'", Concept.findConcept(id));
    }
    
}
