// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import java.util.List;
import org.inqle.domain.ConceptTranslation;
import org.inqle.domain.ConceptTranslationDataOnDemand;
import org.inqle.domain.ConceptTranslationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConceptTranslationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConceptTranslationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConceptTranslationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConceptTranslationIntegrationTest: @Transactional;
    
    @Autowired
    ConceptTranslationDataOnDemand ConceptTranslationIntegrationTest.dod;
    
    @Test
    public void ConceptTranslationIntegrationTest.testCountConceptTranslations() {
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", dod.getRandomConceptTranslation());
        long count = ConceptTranslation.countConceptTranslations();
        Assert.assertTrue("Counter for 'ConceptTranslation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testFindConceptTranslation() {
        ConceptTranslation obj = dod.getRandomConceptTranslation();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to provide an identifier", id);
        obj = ConceptTranslation.findConceptTranslation(id);
        Assert.assertNotNull("Find method for 'ConceptTranslation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConceptTranslation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testFindAllConceptTranslations() {
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", dod.getRandomConceptTranslation());
        long count = ConceptTranslation.countConceptTranslations();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConceptTranslation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConceptTranslation> result = ConceptTranslation.findAllConceptTranslations();
        Assert.assertNotNull("Find all method for 'ConceptTranslation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConceptTranslation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testFindConceptTranslationEntries() {
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", dod.getRandomConceptTranslation());
        long count = ConceptTranslation.countConceptTranslations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConceptTranslation> result = ConceptTranslation.findConceptTranslationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConceptTranslation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConceptTranslation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testFlush() {
        ConceptTranslation obj = dod.getRandomConceptTranslation();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to provide an identifier", id);
        obj = ConceptTranslation.findConceptTranslation(id);
        Assert.assertNotNull("Find method for 'ConceptTranslation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConceptTranslation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConceptTranslation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testMergeUpdate() {
        ConceptTranslation obj = dod.getRandomConceptTranslation();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to provide an identifier", id);
        obj = ConceptTranslation.findConceptTranslation(id);
        boolean modified =  dod.modifyConceptTranslation(obj);
        Integer currentVersion = obj.getVersion();
        ConceptTranslation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConceptTranslation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", dod.getRandomConceptTranslation());
        ConceptTranslation obj = dod.getNewTransientConceptTranslation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConceptTranslation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ConceptTranslation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConceptTranslationIntegrationTest.testRemove() {
        ConceptTranslation obj = dod.getRandomConceptTranslation();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptTranslation' failed to provide an identifier", id);
        obj = ConceptTranslation.findConceptTranslation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ConceptTranslation' with identifier '" + id + "'", ConceptTranslation.findConceptTranslation(id));
    }
    
}
