// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import org.inqle.domain.ParticipantIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ParticipantIntegrationTest_Roo_Configurable {
    
    declare @type: ParticipantIntegrationTest: @Configurable;
    
}
