// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inqle.domain.Participant;
import org.inqle.domain.ParticipantDataOnDemand;
import org.inqle.domain.security.Principal;
import org.springframework.stereotype.Component;

privileged aspect ParticipantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParticipantDataOnDemand: @Component;
    
    private Random ParticipantDataOnDemand.rnd = new SecureRandom();
    
    private List<Participant> ParticipantDataOnDemand.data;
    
    public Participant ParticipantDataOnDemand.getNewTransientParticipant(int index) {
        Participant obj = new Participant();
        setCreated(obj, index);
        setCreatedBy(obj, index);
        setUpdated(obj, index);
        setUpdatedBy(obj, index);
        return obj;
    }
    
    public void ParticipantDataOnDemand.setCreated(Participant obj, int index) {
        Date created = new Date(new Date().getTime() + 10000000L);
        obj.setCreated(created);
    }
    
    public void ParticipantDataOnDemand.setCreatedBy(Participant obj, int index) {
        Principal createdBy = null;
        obj.setCreatedBy(createdBy);
    }
    
    public void ParticipantDataOnDemand.setUpdated(Participant obj, int index) {
        Date updated = new Date(new Date().getTime() + 10000000L);
        obj.setUpdated(updated);
    }
    
    public void ParticipantDataOnDemand.setUpdatedBy(Participant obj, int index) {
        Principal updatedBy = null;
        obj.setUpdatedBy(updatedBy);
    }
    
    public Participant ParticipantDataOnDemand.getSpecificParticipant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Participant obj = data.get(index);
        Long id = obj.getId();
        return Participant.findParticipant(id);
    }
    
    public Participant ParticipantDataOnDemand.getRandomParticipant() {
        init();
        Participant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Participant.findParticipant(id);
    }
    
    public boolean ParticipantDataOnDemand.modifyParticipant(Participant obj) {
        return false;
    }
    
    public void ParticipantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Participant.findParticipantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Participant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Participant>();
        for (int i = 0; i < 10; i++) {
            Participant obj = getNewTransientParticipant(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
