// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.inqle.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.inqle.domain.Account;
import org.inqle.domain.Concept;
import org.inqle.domain.ConceptDataOnDemand;
import org.inqle.domain.Question;
import org.inqle.domain.QuestionDataOnDemand;
import org.inqle.service.Asker;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect QuestionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuestionDataOnDemand: @Component;
    
    private Random QuestionDataOnDemand.rnd = new SecureRandom();
    
    private List<Question> QuestionDataOnDemand.data;
    
    @Autowired
    ConceptDataOnDemand QuestionDataOnDemand.conceptDataOnDemand;
    
    @Autowired
    Asker QuestionDataOnDemand.asker;
    
    public Question QuestionDataOnDemand.getNewTransientQuestion(int index) {
        Question obj = new Question();
        setChronicity(obj, index);
        setConcept(obj, index);
        setCreated(obj, index);
        setCreatedBy(obj, index);
        setLang(obj, index);
        setUpdated(obj, index);
        setUpdatedBy(obj, index);
        return obj;
    }
    
    public void QuestionDataOnDemand.setChronicity(Question obj, int index) {
        Integer chronicity = new Integer(index);
        if (chronicity < 0 || chronicity > 256) {
            chronicity = 256;
        }
        obj.setChronicity(chronicity);
    }
    
    public void QuestionDataOnDemand.setConcept(Question obj, int index) {
        Concept concept = conceptDataOnDemand.getRandomConcept();
        obj.setConcept(concept);
    }
    
    public void QuestionDataOnDemand.setCreated(Question obj, int index) {
        Date created = new Date(new Date().getTime() + 10000000L);
        obj.setCreated(created);
    }
    
    public void QuestionDataOnDemand.setCreatedBy(Question obj, int index) {
        Account createdBy = null;
        obj.setCreatedBy(createdBy);
    }
    
    public void QuestionDataOnDemand.setLang(Question obj, int index) {
        String lang = "lang_" + index;
        obj.setLang(lang);
    }
    
    public void QuestionDataOnDemand.setUpdated(Question obj, int index) {
        Date updated = new Date(new Date().getTime() + 10000000L);
        obj.setUpdated(updated);
    }
    
    public void QuestionDataOnDemand.setUpdatedBy(Question obj, int index) {
        Account updatedBy = null;
        obj.setUpdatedBy(updatedBy);
    }
    
    public Question QuestionDataOnDemand.getSpecificQuestion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Question obj = data.get(index);
        Long id = obj.getId();
        return asker.findQuestion(id);
    }
    
    public Question QuestionDataOnDemand.getRandomQuestion() {
        init();
        Question obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return asker.findQuestion(id);
    }
    
    public boolean QuestionDataOnDemand.modifyQuestion(Question obj) {
        return false;
    }
    
    public void QuestionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = asker.findQuestionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Question' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Question>();
        for (int i = 0; i < 10; i++) {
            Question obj = getNewTransientQuestion(i);
            try {
                asker.saveQuestion(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
