package com.beyobe.client.beans;

public enum Message {
	SIGNUP_FAILURE_ACCTOUNT_EXISTS, 
//	QUESTION_QUEUE_RETURNED, 
	MATCHING_QUESTIONS_RETURNED, 
	ALL_DATA_RETRIEVED, 
	SIGNED_UP, 
	SAVED, 
	UNSUBSCRIBED,
	SUBSCRIPTION_NOT_FOUND, 
	TOO_MANY_QUESTIONS,
	TOO_MANY_DATA,
	BAD_REQUEST, 
	LOGIN_FAILED, 
	LOGIN_SUCCEEDED, 
	INVALID_SESSION, 
	UNSUBSCRIBE_FAILED, 
	SAVE_FAILED, 
	SUBSCRIBE_FAILED
}
